### ISSUE TITLE
Sipeed license server for Gowin IDE is offline.

### ISSUE THREAD

**Issue by kprasadvnsi** [sipeed/Tang-Nano-Doc#1]
License server IP 50.116.30.241 given in docs is not working. If it is running on different IP then please update it in the docs.

**Comment by Zepan** [comment]
it is update to 45.33.107.56

**Comment by kprasadvnsi** [comment]
Thanks for the update.

**Comment by xjtuecho** [comment]
> it is update to 45.33.107.56

45.33.107.56 is not working now.

**Comment by paller** [comment]
> 

I can't use it neither.

**Comment by AntonioDrusin** [comment]
Having the same issue. Server not responding.
![image](https://user-images.githubusercontent.com/3536083/144768121-f171d0d9-647a-498f-a22d-007174fd763d.png)

**Comment by cybekRT** [comment]
Any update?

**Comment by Strontium00** [comment]
Same here, any news?

**Comment by cybekRT** [comment]
Responded on the issue #7

**Comment by AntonioDrusin** [comment]
Installing GOWIN FPGA Designer  Version 1.9.8 build(54687) has worked for me. I was able to get a license.
Also 1.9.8 works better with the Sipeed cards, for example 1.9.8.01 is not able to program the internal FLASH (it is not possible to change the USB cable speed on the windows installation of that version).
